version: "3"
services:
  pt:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    # environment:
    #   - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./workspace:/workspace
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    command: jupyter lab --allow-root
